package com.databundleHum.OnetBundleHub.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Immutable ledger entry. Every wallet mutation produces exactly one row here.
 * The wallet balance on the users table is kept in sync; this table is the audit trail.
 *
 * ── Transaction type reference ────────────────────────────────────────────────
 *
 *  TOPUP                        — wallet credited via Paystack top-up
 *  PURCHASE                     — wallet debited for a data bundle order
 *  RESELLER_FEE                 — GHS 20 deducted on reseller application
 *  PAYOUT                       — reseller profit paid out (debits wallet on admin approval)
 *  REFUND                       — order refund credited back to wallet after failed delivery
 *  ADMIN_CREDIT                 — wallet credit manually applied by a Super Admin
 *  ADMIN_DEBIT                  — wallet debit manually applied by a Super Admin
 *  AFFILIATE_COMMISSION         — 2% commission credited when a referred user's order delivers
 *  AFFILIATE_COMMISSION_REVERSAL— commission clawed back when the underlying order is refunded
 */
@Entity
@Table(name = "wallet_transactions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class WalletTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 40)   // bumped from 20 — AFFILIATE_COMMISSION_REVERSAL = 30 chars
    private TransactionType type;

    /**
     * Absolute amount in GHS (always positive).
     * Direction (credit vs debit) is inferred from the TransactionType:
     *   Credits: TOPUP, REFUND, ADMIN_CREDIT, AFFILIATE_COMMISSION
     *   Debits:  PURCHASE, RESELLER_FEE, PAYOUT, ADMIN_DEBIT, AFFILIATE_COMMISSION_REVERSAL
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    /** Snapshot of the wallet balance immediately after this transaction. */
    @Column(name = "balance_after", nullable = false, precision = 12, scale = 2)
    private BigDecimal balanceAfter;

    /** Paystack reference, internal order reference, or payout reference. */
    @Column(length = 100)
    private String reference;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    // ── Enums ─────────────────────────────────────────────────────────────────

    public enum TransactionType {

        /** Wallet credited via Paystack top-up (manual or webhook). */
        TOPUP,

        /** Wallet debited for a data bundle purchase (user or reseller direct order). */
        PURCHASE,

        /** GHS 20 registration fee debited when a user applies to become a reseller. */
        RESELLER_FEE,

        /**
         * Reseller profit paid out to mobile money.
         * Debited from wallet when admin marks the payout PAID.
         */
        PAYOUT,

        /**
         * Wallet credited when a bundle delivery fails after the wallet was debited.
         * Also used when an admin rejects a reseller application (registration fee refund).
         */
        REFUND,

        /** Wallet credit applied manually by a Super Admin with an audit reason. */
        ADMIN_CREDIT,

        /** Wallet debit applied manually by a Super Admin with an audit reason. */
        ADMIN_DEBIT,

        /**
         * 2% affiliate commission credited to the referring affiliate's wallet
         * when a referred user's order is successfully delivered (status → VERIFIED).
         *
         * Generated by: AffiliateCommissionService.processCommission()
         */
        AFFILIATE_COMMISSION,

        /**
         * Commission clawed back from the affiliate's wallet when the underlying
         * order is refunded (status → FAILED after having been VERIFIED).
         *
         * Generated by: AffiliateCommissionService.reverseCommission()
         * The corresponding CommissionTransaction row is flagged reversed = true.
         */
        AFFILIATE_COMMISSION_REVERSAL
    }
}
