package com.databundleHum.OnetBundleHub.services;

import com.databundleHum.OnetBundleHub.security.UpstreamApiException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Facade over the Big Dreams Data Developer API.
 *
 * Rebuilt from scratch — the original BigDreamsService was removed during
 * the 2026-08-26 migration to DataPrimo for data-bundle purchase (see
 * AdminBundleController's Javadoc), but AppConfig's bigDreamsWebClient bean
 * was left in place. This service re-adds the client logic against that
 * same bean, and additionally implements the result-checker, share-balance,
 * and AFA-registration actions the original integration never covered.
 *
 * ── Protocol ────────────────────────────────────────────────────────────
 * Every operation is a POST to the single configured base URL (no extra
 * path segment), with an "action" field in the JSON body selecting the
 * operation, authenticated via the x-api-key header (already set as a
 * WebClient default in AppConfig — not repeated per-call here).
 *
 * ── Response shape ──────────────────────────────────────────────────────
 * Unlike DataBossHub's checker fields (explicitly documented as
 * unconfirmed), Big Dreams Data's docs give concrete, confirmed field
 * names for every action below — so this service parses into typed
 * records rather than defensively guessing candidate keys. Every response
 * follows { "success": bool, "data": {...} } on success, or
 * { "success": false, "error": "...", "message": "..." } on failure.
 *
 * ── Checker restock — the actual reason this file exists again ──────────
 * buyResultChecker() is what AdminCheckerStockController calls when an
 * admin clicks "restock via Big Dreams" — it buys ONE checker credential
 * and returns it for CheckerStock insertion. It does not touch our own
 * platform wallet or CheckerOrder at all; it only debits the Big Dreams
 * Data account balance on their side. See CheckerService.provisionFromStock()
 * for how customer purchases actually get fulfilled (from local stock, not
 * a live call here).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class BigDreamsDataService {

    @Qualifier("bigDreamsWebClient")
    private final WebClient bigDreamsWebClient;
    private final ObjectMapper objectMapper = new ObjectMapper();

    // ══════════════════════════════════════════════════════════════════════
    // Data bundles
    // ══════════════════════════════════════════════════════════════════════

    /**
     * place_order — purchase and send a data bundle to a recipient.
     *
     * @param network     "mtn", "telecel", or "ishare" (AirtelTigo) — exact
     *                    lowercase values per the docs; not validated here.
     * @param recipient   10-digit phone, e.g. "0244123456".
     * @param packageSizeGb bundle size in GB.
     * @param orderId     optional idempotency reference — auto-generated by
     *                    Big Dreams Data if null.
     */
    public PlaceOrderResult placeOrder(String network, String recipient, int packageSizeGb, String orderId) {
        log.info("[BIGDREAMS] place_order: network={} recipient={} packageSizeGb={} orderId={}",
                network, recipient, packageSizeGb, orderId);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "place_order");
        body.put("network", network);
        body.put("recipient", recipient);
        body.put("package_size", packageSizeGb);
        if (orderId != null && !orderId.isBlank()) {
            body.put("order_id", orderId);
        }

        JsonNode data = postForData(body, "place_order");

        PlaceOrderResult result = new PlaceOrderResult(
                text(data, "order_id"),
                data.path("transaction_id").isMissingNode() ? null : data.path("transaction_id").asLong(),
                text(data, "reference"),
                text(data, "network"),
                text(data, "recipient"),
                data.path("package_size").asInt(),
                text(data, "bundle"),
                text(data, "validity"),
                decimal(data, "amount"),
                text(data, "status"),
                decimal(data, "new_balance"),
                text(data, "timestamp")
        );

        log.info("[BIGDREAMS] ✔ place_order succeeded: orderId={} reference={} amount={} newBalance={}",
                result.orderId(), result.reference(), result.amount(), result.newBalance());
        return result;
    }

    public record PlaceOrderResult(
            String orderId, Long transactionId, String reference, String network, String recipient,
            int packageSizeGb, String bundle, String validity, BigDecimal amount, String status,
            BigDecimal newBalance, String timestamp) {}

    /**
     * get_bundles — fetch available bundles with this account's custom
     * pricing applied.
     *
     * @param network optional filter: "mtn", "telecel", or "airteltigo" — null for all.
     */
    public List<BundleListing> getBundles(String network) {
        log.info("[BIGDREAMS] get_bundles: network={}", network == null ? "(all)" : network);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "get_bundles");
        if (network != null && !network.isBlank()) {
            body.put("network", network);
        }

        JsonNode data = postForData(body, "get_bundles");
        List<BundleListing> bundles = new ArrayList<>();
        for (JsonNode b : data.path("bundles")) {
            bundles.add(new BundleListing(
                    b.path("id").asLong(),
                    text(b, "network"),
                    text(b, "size"),
                    b.path("size_gb").asInt(),
                    decimal(b, "price"),
                    text(b, "validity"),
                    b.path("has_custom_price").asBoolean(false)
            ));
        }

        log.info("[BIGDREAMS] ✔ get_bundles: {} bundle(s) returned", bundles.size());
        return bundles;
    }

    public record BundleListing(
            Long id, String network, String size, int sizeGb, BigDecimal price,
            String validity, boolean hasCustomPrice) {}

    // ══════════════════════════════════════════════════════════════════════
    // Wallet
    // ══════════════════════════════════════════════════════════════════════

    /** check_balance — this account's Big Dreams Data wallet balance. */
    public BalanceResult checkBalance() {
        log.info("[BIGDREAMS] check_balance");

        JsonNode data = postForData(Map.of("action", "check_balance"), "check_balance");
        JsonNode user = data.path("user");

        BalanceResult result = new BalanceResult(
                decimal(data, "wallet_balance"),
                text(data, "currency"),
                text(user, "name"),
                text(user, "email")
        );

        log.info("[BIGDREAMS] ✔ check_balance: balance={} {} accountName={}",
                result.balance(), result.currency(), result.accountName());
        return result;
    }

    public record BalanceResult(BigDecimal balance, String currency, String accountName, String accountEmail) {}

    /**
     * get_transactions — paginated transaction history on this Big Dreams
     * Data account.
     */
    public TransactionHistory getTransactions(int limit, int offset) {
        log.info("[BIGDREAMS] get_transactions: limit={} offset={}", limit, offset);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "get_transactions");
        body.put("limit", limit);
        body.put("offset", offset);

        JsonNode data = postForData(body, "get_transactions");
        List<TransactionEntry> transactions = new ArrayList<>();
        for (JsonNode t : data.path("transactions")) {
            transactions.add(new TransactionEntry(
                    t.path("id").asLong(),
                    text(t, "type"),
                    decimal(t, "amount"),
                    text(t, "status"),
                    text(t, "description"),
                    text(t, "created_at")
            ));
        }

        int total = data.path("total").asInt();
        log.info("[BIGDREAMS] ✔ get_transactions: {} of {} total", transactions.size(), total);
        return new TransactionHistory(transactions, data.path("count").asInt(), total);
    }

    public record TransactionEntry(
            Long id, String type, BigDecimal amount, String status, String description, String createdAt) {}

    public record TransactionHistory(List<TransactionEntry> transactions, int count, int total) {}

    // ══════════════════════════════════════════════════════════════════════
    // Result checkers — the feature this integration is actually for
    // ══════════════════════════════════════════════════════════════════════

    /**
     * get_result_checkers — list checker types with this account's price
     * and current stock on the Big Dreams Data side. Useful for the admin
     * UI to preview before restocking, and to sanity-check availability
     * before calling buyResultChecker() in a loop.
     */
    public List<ResultCheckerListing> getResultCheckers() {
        log.info("[BIGDREAMS] get_result_checkers");

        JsonNode data = postForData(Map.of("action", "get_result_checkers"), "get_result_checkers");
        List<ResultCheckerListing> listings = new ArrayList<>();
        for (JsonNode c : data.path("result_checkers")) {
            listings.add(new ResultCheckerListing(
                    text(c, "type"),
                    text(c, "name"),
                    decimal(c, "price"),
                    c.path("available").asBoolean(false),
                    c.path("in_stock").isMissingNode() ? null : c.path("in_stock").asInt()
            ));
        }

        log.info("[BIGDREAMS] ✔ get_result_checkers: {} type(s) returned", listings.size());
        return listings;
    }

    public record ResultCheckerListing(
            String type, String name, BigDecimal price, boolean available, Integer inStock) {}

    /**
     * buy_result_checker — buy ONE checker credential for the given exam
     * type. Debits the Big Dreams Data account balance (their side, not
     * our platform wallet) and returns the serial + PIN immediately.
     *
     * @param productType exact lowercase value expected by the API, e.g.
     *                    "wassce" or "bece" — callers should pass
     *                    examType.name().toLowerCase().
     */
    public BuyCheckerResult buyResultChecker(String productType) {
        log.info("[BIGDREAMS] buy_result_checker: productType={}", productType);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "buy_result_checker");
        body.put("product_type", productType);

        JsonNode data = postForData(body, "buy_result_checker");

        BuyCheckerResult result = new BuyCheckerResult(
                text(data, "name"),
                text(data, "serial"),
                text(data, "pin"),
                decimal(data, "amount"),
                decimal(data, "wallet_balance")
        );

        if (result.serial() == null || result.pin() == null) {
            throw new UpstreamApiException(
                    "Big Dreams Data buy_result_checker response missing serial/pin for productType="
                            + productType);
        }

        log.info("[BIGDREAMS] ✔ buy_result_checker succeeded: productType={} name={} newBalance={}",
                productType, result.name(), result.walletBalance());
        return result;
    }

    public record BuyCheckerResult(String name, String serial, String pin, BigDecimal amount, BigDecimal walletBalance) {}

    // ══════════════════════════════════════════════════════════════════════
    // Special offers
    // ══════════════════════════════════════════════════════════════════════

    /** get_special_offers — list active offers and this account's price. */
    public List<SpecialOfferListing> getSpecialOffers() {
        log.info("[BIGDREAMS] get_special_offers");

        JsonNode data = postForData(Map.of("action", "get_special_offers"), "get_special_offers");
        List<SpecialOfferListing> offers = new ArrayList<>();
        for (JsonNode o : data.path("special_offers")) {
            offers.add(new SpecialOfferListing(
                    o.path("id").asLong(),
                    text(o, "title"),
                    text(o, "description"),
                    decimal(o, "price")
            ));
        }

        log.info("[BIGDREAMS] ✔ get_special_offers: {} offer(s) returned", offers.size());
        return offers;
    }

    public record SpecialOfferListing(Long id, String title, String description, BigDecimal price) {}

    /** buy_special_offer — buy an offer for a customer. */
    public BuySpecialOfferResult buySpecialOffer(long offerId, String recipient) {
        log.info("[BIGDREAMS] buy_special_offer: offerId={} recipient={}", offerId, recipient);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "buy_special_offer");
        body.put("offer_id", offerId);
        body.put("recipient", recipient);

        JsonNode data = postForData(body, "buy_special_offer");

        BuySpecialOfferResult result = new BuySpecialOfferResult(
                text(data, "order_id"),
                decimal(data, "amount"),
                text(data, "status"),
                decimal(data, "new_balance")
        );

        log.info("[BIGDREAMS] ✔ buy_special_offer succeeded: offerId={} orderId={} status={}",
                offerId, result.orderId(), result.status());
        return result;
    }

    public record BuySpecialOfferResult(String orderId, BigDecimal amount, String status, BigDecimal newBalance) {}

    // ══════════════════════════════════════════════════════════════════════
    // Share balances (iShare / Telecel) — separate pool from the wallet
    // ══════════════════════════════════════════════════════════════════════

    /** get_ishare_balance — AirtelTigo iShare balance, denominated in MB. */
    public ShareBalance getIShareBalance() {
        log.info("[BIGDREAMS] get_ishare_balance");
        JsonNode data = postForData(Map.of("action", "get_ishare_balance"), "get_ishare_balance");
        return new ShareBalance(text(data, "network"), decimal(data, "balance"),
                text(data, "unit"), data.path("enabled").asBoolean(false));
    }

    /** get_telecel_balance — Telecel Share balance, denominated in GB. */
    public ShareBalance getTelecelBalance() {
        log.info("[BIGDREAMS] get_telecel_balance");
        JsonNode data = postForData(Map.of("action", "get_telecel_balance"), "get_telecel_balance");
        return new ShareBalance(text(data, "network"), decimal(data, "balance"),
                text(data, "unit"), data.path("enabled").asBoolean(false));
    }

    public record ShareBalance(String network, BigDecimal balance, String unit, boolean enabled) {}

    /**
     * share_ishare — send iShare data (MB) from the pre-loaded share
     * balance (NOT the wallet). Automatically refunded share-side if the
     * provider rejects the order. Reusing the same orderId returns the
     * original order without charging twice.
     */
    public ShareResult shareIShare(String recipient, int mb, String orderId) {
        log.info("[BIGDREAMS] share_ishare: recipient={} mb={} orderId={}", recipient, mb, orderId);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "share_ishare");
        body.put("recipient", recipient);
        body.put("mb", mb);
        if (orderId != null && !orderId.isBlank()) body.put("order_id", orderId);

        JsonNode data = postForData(body, "share_ishare");
        return new ShareResult(text(data, "order_id"), text(data, "recipient"),
                decimal(data, "amount"), text(data, "unit"), text(data, "status"),
                decimal(data, "balance_remaining"));
    }

    /** share_telecel — send Telecel data (GB) from the pre-loaded share balance. */
    public ShareResult shareTelecel(String recipient, BigDecimal gb, String orderId) {
        log.info("[BIGDREAMS] share_telecel: recipient={} gb={} orderId={}", recipient, gb, orderId);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "share_telecel");
        body.put("recipient", recipient);
        body.put("gb", gb);
        if (orderId != null && !orderId.isBlank()) body.put("order_id", orderId);

        JsonNode data = postForData(body, "share_telecel");
        return new ShareResult(text(data, "order_id"), text(data, "recipient"),
                decimal(data, "amount"), text(data, "unit"), text(data, "status"),
                decimal(data, "balance_remaining"));
    }

    public record ShareResult(
            String orderId, String recipient, BigDecimal amount, String unit, String status, BigDecimal balanceRemaining) {}

    // ══════════════════════════════════════════════════════════════════════
    // Order status
    // ══════════════════════════════════════════════════════════════════════

    /**
     * check_status — poll the status of any order placed via place_order,
     * share_ishare, or share_telecel. Docs say to poll no more than once
     * every 30–60 seconds; that throttling is the caller's responsibility.
     */
    public OrderStatusResult checkStatus(String orderReference) {
        log.info("[BIGDREAMS] check_status: orderReference={}", orderReference);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "check_status");
        body.put("order_reference", orderReference);

        JsonNode data = postForData(body, "check_status");
        return new OrderStatusResult(
                text(data, "order_id"),
                text(data, "reference"),
                text(data, "status"),
                text(data, "failure_reason"),
                text(data, "created_at"),
                text(data, "updated_at")
        );
    }

    public record OrderStatusResult(
            String orderId, String reference, String status, String failureReason, String createdAt, String updatedAt) {}

    // ══════════════════════════════════════════════════════════════════════
    // AFA registration
    // ══════════════════════════════════════════════════════════════════════

    /**
     * afa_register — submit an MTN AFA registration on behalf of a
     * customer. Charges this account's AFA fee immediately; refunded
     * automatically if the registration cannot be recorded after charging.
     */
    public AfaRegistrationResult afaRegister(String fullName, String phoneNumber, String ghanaCard,
                                              String dateOfBirth, Map<String, Object> extraData) {
        log.info("[BIGDREAMS] afa_register: fullName={} phone={}", fullName, phoneNumber);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("action", "afa_register");
        body.put("full_name", fullName);
        body.put("phone_number", phoneNumber);
        body.put("ghana_card", ghanaCard);
        if (dateOfBirth != null) body.put("date_of_birth", dateOfBirth);
        if (extraData != null) body.put("extra_data", extraData);

        JsonNode data = postForData(body, "afa_register");
        AfaRegistrationResult result = new AfaRegistrationResult(
                text(data, "registration_id"),
                text(data, "full_name"),
                text(data, "phone_number"),
                decimal(data, "fee"),
                text(data, "status"),
                text(data, "timestamp")
        );

        log.info("[BIGDREAMS] ✔ afa_register submitted: registrationId={} status={}",
                result.registrationId(), result.status());
        return result;
    }

    public record AfaRegistrationResult(
            String registrationId, String fullName, String phoneNumber, BigDecimal fee, String status, String timestamp) {}

    // ══════════════════════════════════════════════════════════════════════
    // Shared request/response plumbing
    // ══════════════════════════════════════════════════════════════════════

    /**
     * Posts an action body to the single Big Dreams Data endpoint, checks
     * the top-level "success" flag, and returns the "data" node — or
     * throws UpstreamApiException with the provider's own error/message on
     * any failure (HTTP error, success:false, or malformed body).
     */
    private JsonNode postForData(Map<String, Object> body, String actionForLogging) {
        try {
            String rawBody = bigDreamsWebClient.post()
                    .bodyValue(body)
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            log.info("[BIGDREAMS] {} raw response: [{}]", actionForLogging, rawBody);

            if (rawBody == null || rawBody.isBlank()) {
                throw new UpstreamApiException(
                        "Big Dreams Data returned an empty response for action=" + actionForLogging);
            }

            JsonNode root = objectMapper.readTree(rawBody);

            if (!root.path("success").asBoolean(false)) {
                String error = text(root, "error");
                String message = text(root, "message");
                throw new UpstreamApiException(
                        "Big Dreams Data rejected action=" + actionForLogging
                                + " — error=" + error + " message=" + message);
            }

            JsonNode data = root.path("data");
            if (data.isMissingNode() || data.isNull()) {
                throw new UpstreamApiException(
                        "Big Dreams Data response for action=" + actionForLogging + " had no data object");
            }
            return data;

        } catch (WebClientResponseException ex) {
            log.error("[BIGDREAMS] HTTP {} on action={}: {}",
                    ex.getStatusCode(), actionForLogging, ex.getResponseBodyAsString());
            throw new UpstreamApiException(
                    "Big Dreams Data HTTP " + ex.getStatusCode() + " for action=" + actionForLogging
                            + " — " + ex.getResponseBodyAsString());
        } catch (UpstreamApiException ex) {
            throw ex;
        } catch (Exception ex) {
            log.error("[BIGDREAMS] Unexpected error on action={} — type={} error={}",
                    actionForLogging, ex.getClass().getSimpleName(), ex.getMessage());
            throw new UpstreamApiException(
                    "Big Dreams Data call failed for action=" + actionForLogging + ": " + ex.getMessage());
        }
    }

    private String text(JsonNode node, String field) {
        JsonNode v = node.path(field);
        return v.isMissingNode() || v.isNull() ? null : v.asText();
    }

    private BigDecimal decimal(JsonNode node, String field) {
        JsonNode v = node.path(field);
        if (v.isMissingNode() || v.isNull()) return null;
        return new BigDecimal(v.asText());
    }
}
